accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.userlist, name='userlist'),
    path('<int:user_pk>/', views.userdetail, name='userdetail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),


]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/reviews/', views.reviews_create, name='reviews_create'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/',
         views.reviews_delete, name='reviews_delete'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),



]

project10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='followings', blank=True)

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    genres = models.ManyToManyField(Genre, related_name='movies')

    def __str__(self):
        return self.title


class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

movies/forms.py
from django import forms
from django.forms import ModelForm
from .models import Movie, Genre, Review

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'audience', 'poster_url', 'description',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from .forms import CustomUserCreationForm
# Create your views here.


def userlist(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'accounts/userlist.html', context)


def userdetail(request, user_pk):
    user1 = get_object_or_404(User, pk=user_pk)
    context = {'user1': user1}
    return render(request, 'accounts/userdetail.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/auth_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/auth_form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('movies:index')

movies/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Genre, Review
from .forms import MovieForm, ReviewForm
from accounts.models import User
from django.views.decorators.http import require_POST

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies, }
    return render(request, 'movies/index.html', context)


def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    reviews = movie.review_set.all()
    review_form = ReviewForm()
    genres = movie.genres.all()
    context = {'movie': movie, 'reviews': reviews,
               'review_form': review_form, 'genres': genres, }
    return render(request, 'movies/detail.html', context)


@require_POST
def reviews_create(request, movie_pk):
    if request.user.is_authenticated:
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie_id = movie_pk
            review.user = request.user
            review.save()
    return redirect('movies:detail', movie_pk)


@require_POST
def reviews_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.user:
            review.delete()
        return redirect('movies:detail', movie_pk)


@login_required
def like(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if movie.like_users.filter(pk=request.user.pk).exists():
        movie.like_users.remove(request.user)
    else:
        movie.like_users.add(request.user)
    return redirect('movies:index')


@login_required
def follow(request, user_pk):
    person = get_object_or_404(User, pk=user_pk)
    user = request.user
    if person != user:
        if person.followers.filter(pk=user.pk).exists():
            person.followers.remove(user)
        else:
            person.followers.add(user)
    return redirect('accounts:userdetail', user_pk)

accounts/templates/accounts/auth_form.html
{% extends 'movies/base.html' %}
{% block content %}
{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% endif %}
<form method="POST">
  {% csrf_token %}
  <p>{{ form }}</p>

  {% if request.resolver_match.url_name == 'signup' %}
  <input type="submit" value="회원가입">
  {% elif request.resolver_match.url_name == 'login' %}
  <input type="submit" value="로그인">
  {% endif %}
</form>
{% endblock %}

accounts/templates/accounts/userdetail.html
{% extends 'movies/base.html' %}
{% block content %}
<h2>{{ user1.username }} 님의 상세 보기</h2>
<hr>
<h4>{{ user1.username }} 님이 리뷰한 영화들</h4>
{% for review in user1.review_set.all %}
<p>영화 : {{ review.movie }}</p>
<p>한 줄 평 :{{ review.content }}</p>
<p>평점 : {{ review.score }}</p>
{% endfor %}
<hr>
<h4>{{ user1.username }} 님이 좋아요한 영화</h4>
{% for movie in user1.like_movies.all  %}
<ul>
  <li>{{ movie }}</li>
</ul>
{% endfor %}
<hr>
{% if user.is_authenticated %}
{% if user in user1.followers.all %}
<a class="btn btn-primary btn-sm" href="{% url 'movies:follow' user1.pk %}" role="button">Unfollow</a>
<!-- person.pk 게시글 쓴 사람??-->
{% else %}
<a class="btn btn-primary btn-sm" href="{% url 'movies:follow' user1.pk %}" role="button">follow</a>
{% endif %}
{% endif %}
<hr>
<h4>Followers : {{ user1.followers.all|length }}</h4>

{% for user in user1.followers.all %}
<ul>
  <li>{{ user }}</li>
</ul>
{% endfor %}
<hr>
<h4>Followings: {{ user1.followings.all|length }}</h4>
{% for user in user1.followings.all %}
<ul>
  <li>{{ user }}</li>
</ul>
{% endfor %}
{% endblock content %}

accounts/templates/accounts/userlist.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <h2>유저 목록입니다.</h2>
  {% if user.is_authenticated %}
  <h3>환영합니다. {{ user }}님</h3>
  {% else %}
  <h3>로그인해주십시오.</h3>
  {% endif %}
  <ul>
    {% for user in users  %}
    <li><a href="{% url 'accounts:userdetail' user.pk %}">{{ user.username }}</a></li>
    <br>
    {% endfor %}
  </ul>
</body>

</html>

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/0321ecdd79.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>

<body>
  <div class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'movies:index' %}">SPH Movies</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout <span
            class="sr-only">(current)</span></a>
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'accounts:signup' %}">Signup <span
            class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login <span
            class="sr-only">(current)</span></a>

        {% endif %}
      </div>
    </div>
  </div>
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block content %}
<h1 class="text-center">DETAIL</h1>
<hr>
<img src="{{ movie.poster_url }}" alt="img"
  style=" border: 1px solid #ddd; border-radius: 4px; padding: 5px; width: 300px;">
<div class="card" style="width: 500px;">
  <div class="card-body">
    <h4 class="card-title">{{ movie.title }}</h4>
    <h6 class="card-subtitle mb-2 text-muted">누적 관객: {{ movie.audience }}</h6>
    <h6><b>줄거리</b></h6>
    <p class="card-text">{{ movie.description }}
    </p>
    {% for genre in genres %}
    <b>{{ genre.name }}</b>
    {% endfor %}
  </div>
</div>


{% for review in reviews %}
<div>
  <h4>댓글
  </h4>
  <a href="{% url 'accounts:userdetail' review.user.pk %}">{{ review.user }}</a> 댓글 {{ forloop.revcounter }} :
  {{ review.content }} / 평점 : {{ review.score }}
  {% if request.user == comment.user %}
  <form action="{% url 'movies:reviews_delete' movie.pk review.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  {% endif %}
</div>
{% empty %}
<p><b>댓글이 없습니다.</b></p>
{% endfor %}
<hr>
{% if request.user.is_authenticated %}
<form action="{% url 'movies:reviews_create' movie.pk %}" method="POST">
  {% csrf_token %}
  {{ review_form }}
  <input type="submit" value="submit">
</form>
<!--
  {% else %}
  <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인 하세요]</a>
  {% endif %}
-->
<hr>
<a href="{% url 'movies:index' %}">[BACK]</a>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block content %}
<h1 class="text-center">Movies List</h1>
<hr>
<div class="row justify-content-between">
  {% for movie in movies %}
  <div class="card mb-3" style="width: 18rem;">
    <a href="{% url 'movies:detail' movie.pk %}"><img src="{{ movie.poster_url }}" class="card-img-top" alt="img"></a>
    <div class="card-body">
      <h5 class="card-title">{{ movie.title }}</h5>
      <a href="{% url 'movies:like' movie.pk %}">
        {% if user in movie.like_users.all %}
        <i class="fab fa-gratipay" style="font-size: 20px; color: crimson;"></i>
        {% else %}
        <i class="fab fa-gratipay" style="font-size: 20px; color: black;"></i>
        {% endif %}
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}